#!/usr/bin/env bash
#
# Regenerate the Quality metrics table in README.md from the actual codebase.
#
# The table previously drifted badly — it claimed ~15,300 Go LOC when the real
# figure was 21,067, and 8 direct dependencies when there were 9 direct plus 43
# indirect. Hand-maintained numbers that restate facts derivable from the code
# are a DRY violation waiting to become a lie, so they are generated instead.
#
# Usage:
#   scripts/update-readme-metrics.sh           # rewrite the table in place
#   scripts/update-readme-metrics.sh --check   # fail if the table is stale (CI)
#
# The table is delimited in README.md by these HTML comment markers:
#   <!-- BEGIN:METRICS --> ... <!-- END:METRICS -->

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${repo_root}"

readme="README.md"
begin_marker="<!-- BEGIN:METRICS -->"
end_marker="<!-- END:METRICS -->"

# --- collect metrics -------------------------------------------------------
#
# Note: these deliberately avoid `... | tail -1` on an xargs pipeline. tail closes
# the pipe as soon as it has its line, xargs/wc then take SIGPIPE, and `pipefail`
# turns that into a silent non-zero exit. Summing with awk reads the whole stream
# and is also correct when xargs splits into several wc invocations (each of which
# emits its own "total" line).

sum_lines() {
  # Reads a newline-separated file list on stdin, prints the total line count.
  #
  # Deliberately loops rather than piping to `xargs wc -l`: git can list a path
  # that no longer exists on disk (an intent-to-add entry for a deleted file, for
  # instance), wc then fails, xargs exits non-zero, and `pipefail` turns that into
  # a silent abort with no diagnostic. Skipping missing paths is both robust and
  # correct here.
  local f n total=0
  while IFS= read -r f; do
    [[ -f "$f" ]] || continue
    n=$(wc -l < "$f" | tr -d ' ')
    total=$(( total + n ))
  done
  printf '%s\n' "${total}"
}

# Track the working tree (cached + untracked-but-not-ignored) so the numbers are
# accurate locally as well as in a clean CI checkout.
list_go() { git ls-files --cached --others --exclude-standard '*.go'; }

prod_loc=$(list_go | grep -v '_test\.go$' | sum_lines)
test_loc=$(list_go | grep '_test\.go$' | sum_lines)
test_funcs=$(list_go | grep '_test\.go$' | while IFS= read -r f; do
  [[ -f "$f" ]] && grep -hoE '^func (Test|Benchmark|Fuzz)[A-Za-z0-9_]*' "$f" || true
done | wc -l | tr -d ' ')

pkg_total=$(go list ./... 2>/dev/null | wc -l | tr -d ' ')
pkg_tested=$(go list -f '{{if or .TestGoFiles .XTestGoFiles}}{{.ImportPath}}{{end}}' ./... 2>/dev/null | grep -c . || true)

direct_deps=$(awk '/^require \(/,/^\)/' go.mod | grep -v '// indirect' | grep -cE '^[[:space:]]+[a-z]' || true)
indirect_deps=$(grep -c '// indirect' go.mod || true)

agent_count=$(git ls-files --cached --others --exclude-standard 'agents/*.md' | wc -l | tr -d ' ')
skill_count=$(git ls-files --cached --others --exclude-standard 'skills/*.md' | wc -l | tr -d ' ')
go_version=$(awk '/^go /{print $2; exit}' go.mod)

# Numbers are emitted as plain digits. Thousands separators were tried and
# removed: printf's %'d separator is locale-dependent (a space under some
# locales) and a portable sed/awk grouper is more machinery than the readability
# gain justifies. Plain digits render identically on every machine, which is what
# matters for a file that is committed and diffed.
fmt_num() { printf '%s' "$1"; }

# --- render ---------------------------------------------------------------

table=$(cat <<EOF
${begin_marker}
<!-- Generated by scripts/update-readme-metrics.sh — do not edit by hand. -->

| Metric | Value |
|--------|-------|
| Test functions | $(fmt_num "${test_funcs}") |
| Test LOC / production LOC | $(fmt_num "${test_loc}") / $(fmt_num "${prod_loc}") |
| Packages tested | ${pkg_tested}/${pkg_total} |
| Go LOC (production) | ~$(fmt_num "${prod_loc}") |
| Dependencies | ${direct_deps} direct, ${indirect_deps} indirect |
| Agents | ${agent_count} |
| Curated skills | ${skill_count} |
| Go version | ${go_version} |
| CI | GitHub Actions (vet + build + \`govulncheck\` + \`staticcheck\` + file-size ratchet + \`-race\` tests) |
| Releases | goreleaser (4 platform binaries on tag) |
| Agent lint | \`moonbase lint\` validates all ${agent_count} agents |
${end_marker}
EOF
)

if ! grep -q "${begin_marker}" "${readme}"; then
  echo "error: ${begin_marker} not found in ${readme}." >&2
  echo "Add the marker pair around the Quality table first." >&2
  exit 1
fi

# Replace the marked block. Done in bash rather than awk because BSD awk (macOS)
# rejects a multi-line value passed via -v, and $table spans many lines.
tmp=$(mktemp)
in_block=0
while IFS= read -r line || [[ -n "$line" ]]; do
  case "$line" in
    *"${begin_marker}"*)
      printf '%s\n' "${table}"
      in_block=1
      continue
      ;;
    *"${end_marker}"*)
      in_block=0
      continue
      ;;
  esac
  (( in_block )) || printf '%s\n' "$line"
done < "${readme}" > "${tmp}"

if [[ "${1:-}" == "--check" ]]; then
  if diff -q "${readme}" "${tmp}" >/dev/null; then
    rm -f "${tmp}"
    echo "README metrics are up to date."
    exit 0
  fi
  echo "README metrics are stale. Diff:" >&2
  diff "${readme}" "${tmp}" >&2 || true
  echo >&2
  echo "Regenerate with: scripts/update-readme-metrics.sh" >&2
  rm -f "${tmp}"
  exit 1
fi

mv "${tmp}" "${readme}"
echo "README metrics updated:"
echo "  production LOC : $(fmt_num "${prod_loc}")"
echo "  test LOC       : $(fmt_num "${test_loc}")"
echo "  test funcs     : $(fmt_num "${test_funcs}")"
echo "  packages       : ${pkg_tested}/${pkg_total} tested"
echo "  dependencies   : ${direct_deps} direct, ${indirect_deps} indirect"
